name: onenessmovement
favicon: null
layout_spectrum: 0.49461
typography_spectrum: 0.49422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00091a'
    - '#c1c1c1'
    - '#144a6e'
    - '#5789a4'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.9700015615671873
purpose: []
