name: onenessmovement
favicon: null
layout_spectrum: 0.1127
typography_spectrum: 0.49422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2c2c2c'
    - '#ececec'
    - '#fbfbfb'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.9700015615671873
purpose: []
